### ISSUE TITLE
Can't update idena-node version in Synology.

### ISSUE THREAD

**Issue by bonezoo** [Rinzler78/docker.idena-node#1]
Hi Rinzer
thank you for your contributing. 
i am using your image on Synology NAS, i am from China, we can't access  some webside due to some reason unless we use VPN. please see below screenshot. it stopped there.
do you have a way to solve it ?
i can download node from PC and upload to datadir folder.
can you make software detect node from there before download from github ?
if exit in the folder then copy to contaainer.

Thank you. 
Best regards.

![Snipaste_2020-10-11_11-17-00](https://user-images.githubusercontent.com/65487667/95669686-ea21c580-0bb5-11eb-80d8-bbb2db5bbe96.png)

**Comment by Rinzler78** [comment]
Hi,

And thanks for using my docker images.
I don't know why it's blocking here, but it seems that you can't access the
binary using the link but you have no errors...
Could you try to download images using this link from a computer on the
same network?

Regards
Boris LECLERE

**Comment by bonezoo** [comment]
Hi
Thanks for your reply.
Because of China Network control, i can't access github. i must use VPN on my PC.
Do you have plan to add function like i said ?

Thank you.
Best Regards.

**Comment by Rinzler78** [comment]
Hi,

Ok.. I've not planned to improve the docker because you are the first encountering the problem.
But i think i could embed the binary into the docker images to be ready to work at first launch.

I will check that and come back to you.

Regards

**Comment by Rinzler78** [comment]
Hi,

I've made changes like i said.
idena-node binary is embed in the docker image and i also make all distro updates.

Please tel me if it's good for you.

Regards

**Comment by bonezoo** [comment]
Hi 
Thank you. i still can't run it.
i can see below information on docker terminal
*Starting openBSD Secure Shell server sshd         [ok]
Starting idena-node
segmentation fault

**Comment by Rinzler78** [comment]
Hi,

So it another problem.
I close current issue and open another.

Talk on it.

Bye
